spring:
  application: {name: signIn}
  datasource: {type: com.zaxxer.hikari.HikariDataSource, driver-class-name: com.mysql.cj.jdbc.Driver,
    url: 'jdbc:mysql://localhost:3306/internet', username: root, password: ry200310}
mybatis:
  type-aliases-package: com.sign.signin.bean
  mapper-locations: classpath:/mapper/*.xml, classpath:/mapper/task/*.xml
  configuration: {map-underscore-to-camel-case: true, lazy-loading-enabled: true}